# Generated by Django 3.2.18 on 2023-04-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0003_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
